{{- range $job_name, $job_config :=  .Values.secor_jobs }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-config
  namespace: {{ $.Values.secor_namespace }}
  labels:
    app: {{ template "secor.appConfigName" }}-config
    chart: {{ $.Chart.Name }}-{{ $.Chart.Version }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
data:
{{- $secor_job_name := $.Release.Name }}
{{ (tpl ($.Files.Glob "config/*").AsConfig $ ) | indent 2 }}
{{- end }}
